/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brazorobotico;

import com.panamahitek.ArduinoException;
import com.panamahitek.PanamaHitek_Arduino;
import java.util.logging.Level;
import java.util.logging.Logger;
import jssc.SerialPortException;


public class BrazoRobotico extends javax.swing.JFrame {

    PanamaHitek_Arduino ino = new PanamaHitek_Arduino();

    /**
     * Creates new form BrazoRobotico1
     */
    public BrazoRobotico() {
        initComponents();
        conexion();
    }

    public void conexion() { // coneccion 
        try {
            ino.arduinoTX("COM4", 9600);
        } catch (ArduinoException ex) {
            Logger.getLogger(BrazoRobotico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void enviardatos(String Dato) { // Enviar Datos
        try { // ENVIA LOS DATOS QUE SE GENEREN
            ino.sendData(Dato);
        } catch (ArduinoException ex) {
            Logger.getLogger(BrazoRobotico.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SerialPortException ex) {
            Logger.getLogger(BrazoRobotico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonGarra = new javax.swing.JButton();
        BotonCodo = new javax.swing.JButton();
        BotonHombre = new javax.swing.JButton();
        BotonBase = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JtextGarra = new javax.swing.JTextField();
        JtextCodo = new javax.swing.JTextField();
        JtextHombro = new javax.swing.JTextField();
        JtextBase = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonGarra.setText("OK");
        BotonGarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGarraActionPerformed(evt);
            }
        });

        BotonCodo.setText("OK");
        BotonCodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCodoActionPerformed(evt);
            }
        });

        BotonHombre.setText("OK");
        BotonHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonHombreActionPerformed(evt);
            }
        });

        BotonBase.setText("OK");
        BotonBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBaseActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brazorobotico/itl.JPG"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel2.setText("Garra");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Modifique los  angulos  del brazo robotico.");

        jLabel4.setText("Codo");

        jLabel5.setText("Hombro");

        jLabel6.setText("Base");

        JtextGarra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtextGarra.setText("jTextField1");
        JtextGarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextGarraActionPerformed(evt);
            }
        });

        JtextCodo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtextCodo.setText("jTextField2");
        JtextCodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextCodoActionPerformed(evt);
            }
        });

        JtextHombro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtextHombro.setText("jTextField3");
        JtextHombro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextHombroActionPerformed(evt);
            }
        });

        JtextBase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtextBase.setText("jTextField4");
        JtextBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextBaseActionPerformed(evt);
            }
        });

        jButton1.setText("Limpiar campos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Abortar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                    .addComponent(BotonGarra))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BotonCodo))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BotonHombre))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BotonBase)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jButton1)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JtextGarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JtextHombro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JtextBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JtextCodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(BotonGarra)
                    .addComponent(JtextGarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCodo)
                    .addComponent(jLabel4)
                    .addComponent(JtextCodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonHombre)
                    .addComponent(jLabel5)
                    .addComponent(JtextHombro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonBase)
                    .addComponent(jLabel6)
                    .addComponent(JtextBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonHombreActionPerformed
        // TODO add your handling code here:
        enviardatos( JtextHombro.getText());
        JtextHombro.setText("");
    }//GEN-LAST:event_BotonHombreActionPerformed

    private void BotonGarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGarraActionPerformed
        // TODO add your handling code here:
         enviardatos(JtextGarra.getText());
        JtextGarra.setText("");
    }//GEN-LAST:event_BotonGarraActionPerformed

    private void BotonCodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCodoActionPerformed
        // TODO add your handling code here:
        enviardatos(JtextCodo.getText());
        JtextCodo.setText("");
    }//GEN-LAST:event_BotonCodoActionPerformed

    private void BotonBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBaseActionPerformed
        // TODO add your handling code here:
        enviardatos(JtextBase.getText());
        JtextBase.setText("");
    }//GEN-LAST:event_BotonBaseActionPerformed

    private void JtextGarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextGarraActionPerformed
        // TODO add your handling code here:
        enviardatos(JtextGarra.getText());
        JtextGarra.setText("");
    }//GEN-LAST:event_JtextGarraActionPerformed

    private void JtextCodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextCodoActionPerformed
        // TODO add your handling code here:
        enviardatos(JtextCodo.getText());
        JtextCodo.setText("");
    }//GEN-LAST:event_JtextCodoActionPerformed

    private void JtextHombroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextHombroActionPerformed
        // TODO add your handling code here:
        enviardatos(JtextHombro.getText());
        JtextHombro.setText("");
    }//GEN-LAST:event_JtextHombroActionPerformed

    private void JtextBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextBaseActionPerformed
        // TODO add your handling code here:
        enviardatos(JtextBase.getText());
        JtextBase.setText("");
    }//GEN-LAST:event_JtextBaseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JtextBase.setText("");
        JtextHombro.setText("");
        JtextCodo.setText("");
        JtextGarra.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrazoRobotico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrazoRobotico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrazoRobotico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrazoRobotico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrazoRobotico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBase;
    private javax.swing.JButton BotonCodo;
    private javax.swing.JButton BotonGarra;
    private javax.swing.JButton BotonHombre;
    private javax.swing.JTextField JtextBase;
    private javax.swing.JTextField JtextCodo;
    private javax.swing.JTextField JtextGarra;
    private javax.swing.JTextField JtextHombro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

 
}



